### ISSUE TITLE
[Feature request] Support GitHub Enterprise

### ISSUE THREAD

**Issue by blastik** [zephraph/atom-github-notifications#7]
Perhaps you could parametrise the github API address in order to support GitHub Enterprise?

Thanks!
D.

**Comment by just-be-dev** [comment]
Yeah, I can do that. Do you need just the root URL? So, not `https://api.github.com` but... something else?

**Comment by blastik** [comment]
yup i think that'd be enough because you support token auth too.
https://developer.github.com/enterprise/2.13/v3/
